// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"golang-restful-api/app"
	"golang-restful-api/controller"
	"golang-restful-api/middleware"
	"golang-restful-api/repository"
	"golang-restful-api/server"
	"golang-restful-api/service"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepositoryImplementation := repository.NewCategoryRepositoryImplementation()
	db := app.NewDB()
	validate := validator.New()
	categoryServiceImplementation := service.NewCategoryServiceImplementation(categoryRepositoryImplementation, db, validate)
	categoryControllerImplementation := controller.NewCategoryControllerImplementation(categoryServiceImplementation)
	router := app.NewRouter(categoryControllerImplementation)
	authMiddleware := middleware.NewAuthMiddleware(router)
	httpServer := server.NewServer(authMiddleware)
	return httpServer
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepositoryImplementation, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImplementation)), service.NewCategoryServiceImplementation, wire.Bind(new(service.CategoryService), new(*service.CategoryServiceImplementation)), controller.NewCategoryControllerImplementation, wire.Bind(new(controller.CategoryController), new(*controller.CategoryControllerImplementation)))
